# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - feature/**
  # pull_request:
    # branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    # strategy:
      # matrix:
        # node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    # - name: Use Node.js ${{ matrix.node-version }}
    - name: Use Node.js 12.22.6
      uses: actions/setup-node@v2
      with:
        # node-version: ${{ matrix.node-version }}
        node-version: 12.22.6
        cache: 'npm'
    - name: Install NPM packages
      run: npm ci
    # - run: npm run build --if-present
    - name: Run lint
      run: npm run lint
    - name: Run build
      run: npm run build --if-present

  test:
    needs:
      - build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.22.6
      uses: actions/setup-node@v2
      with:
        node-version: 12.22.6
        cache: 'npm'
    - name: Install NPM packages
      run: npm ci
    - name: Run tests
      run: npm run test
